### PR TITLE
Kicad 6 integration

### PR DESCRIPTION
**Pull request by evantandersen**
This is a first stab at getting library-loader to automatically place devices into a single kicad symbol and footprint library. KiCAD automatically detects changes to these libraries on the fly, which lets you to go straight from a parts supplier to placing the component in the schematic. It's working well, compatible with KiCAD 6/7.

### CODE REVIEW

**Comment by boyesm** [comment]
This is a great PR. Thank you for implementing this.

**Comment by olback** [comment]
Hi, thanks a lot for this PR!

Can @boyesm or @evantandersen confirm that it works?

**Comment by evantandersen** [comment]
Works well for me, although I've only tested on Linux. Can't see any reasons it won't work on other OSes though.

**Comment by boyesm** [comment]
It worked for me on macOS.

**Pull request merged**
