### PR TITLE
Extract 3D Models and ignore non-zip files

### LINKED ISSUE #15: 3D Models
It would be nice to also extract the 3D Models if available.

Kind Regards,
Stefan

### PR DESCRIPTION
**Pull request by elektro-wolle**
This should fix #15, I also added a check for the extension of new files in the watcher.

### CODE REVIEW

**Comment by j4m3s** [comment]
This would be really handy, is there any chance it will be merged?  Thank you :)

**Comment by elektro-wolle** [comment]
Merged current master into PR.
But is this program still necessary? Currently, the zip-files contains all files and the additional download via the `model.php?partID=` resolves to the same file, that can be downloaded directly from componentsearchengine.

**Comment by olback** [comment]
@elektro-wolle The ZIP files downloaded from Mouser and others do not contain any component files. It's just an EPW file that points to another ZIP file. 

I'm currently re-writing the whole thing to support multiple output formats.

**Comment by olback** [comment]
Version 0.3.0 now supports multiple formats. If any features are missing, please open a new PR.

**Pull request closed without merging**
